# Generated by Django 2.2 on 2019-01-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamreal',
            name='online',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
    ]
